from enum import Enum


class OccupancyType(str, Enum):
    OFFICE = "OFFICE"
    RESIDENTIAL = "RESIDENTIAL"
    MIXED_USE = "MIXED_USE"
    RETAIL = "RETAIL"
    INDUSTRIAL = "INDUSTRIAL"
    EDUCATIONAL = "EDUCATIONAL"
    HEALTHCARE = "HEALTHCARE"
    HOSPITALITY = "HOSPITALITY"
    PARKING = "PARKING"


class MaterialPreference(str, Enum):
    REINFORCED_CONCRETE = "REINFORCED_CONCRETE"
    STRUCTURAL_STEEL = "STRUCTURAL_STEEL"
    COMPOSITE = "COMPOSITE"
    TIMBER = "TIMBER"
    MASONRY = "MASONRY"


class WallType(str, Enum):
    STRUCTURAL = "STRUCTURAL"
    PARTITION = "PARTITION"
    SHEAR_WALL = "SHEAR_WALL"
    RETAINING = "RETAINING"
    FACADE = "FACADE"


class OpeningType(str, Enum):
    DOOR = "DOOR"
    WINDOW = "WINDOW"
    GARAGE_DOOR = "GARAGE_DOOR"
    CURTAIN_WALL = "CURTAIN_WALL"


class CoreType(str, Enum):
    ELEVATOR_STAIR = "ELEVATOR_STAIR"
    STAIR_ONLY = "STAIR_ONLY"
    ELEVATOR_ONLY = "ELEVATOR_ONLY"
    SERVICE = "SERVICE"
    MEP = "MEP"


class RoomType(str, Enum):
    OFFICE = "OFFICE"
    CORRIDOR = "CORRIDOR"
    LOBBY = "LOBBY"
    BATHROOM = "BATHROOM"
    KITCHEN = "KITCHEN"
    BEDROOM = "BEDROOM"
    LIVING_ROOM = "LIVING_ROOM"
    STORAGE = "STORAGE"
    MECHANICAL = "MECHANICAL"
    STAIRWELL = "STAIRWELL"
    ELEVATOR = "ELEVATOR"
    CONFERENCE = "CONFERENCE"
    OUTDOOR = "OUTDOOR"
    UNDEFINED = "UNDEFINED"


class InputSource(str, Enum):
    STRUCTURED_FORM = "STRUCTURED_FORM"
    DXF_FILE = "DXF_FILE"
    DWG_FILE = "DWG_FILE"
    IFC_FILE = "IFC_FILE"
    FLOOR_PLAN_IMAGE = "FLOOR_PLAN_IMAGE"


class RoofType(str, Enum):
    FLAT = "FLAT"
    PITCHED = "PITCHED"
    HIPPED = "HIPPED"
    GABLE = "GABLE"
