"""Enumerations for the Phase 2 Structural Design Graph."""

from __future__ import annotations

from enum import Enum


class StructuralZoneType(str, Enum):
    OPEN_FLOOR_PLATE = "OPEN_FLOOR_PLATE"
    CORE_SERVICE = "CORE_SERVICE"
    PERIMETER = "PERIMETER"
    CORRIDOR_BAND = "CORRIDOR_BAND"
    TRANSFER_RISK = "TRANSFER_RISK"
    HIGH_CLEARANCE = "HIGH_CLEARANCE"
    SUPPORT_FRIENDLY = "SUPPORT_FRIENDLY"
    SUPPORT_AVERSE = "SUPPORT_AVERSE"
    DOUBLE_HEIGHT = "DOUBLE_HEIGHT"
    LARGE_OPENING = "LARGE_OPENING"


class SupportCandidateClass(str, Enum):
    STRONG = "STRONG"
    SECONDARY = "SECONDARY"
    WEAK = "WEAK"
    FORBIDDEN = "FORBIDDEN"


class SupportCandidateReason(str, Enum):
    GRID_INTERSECTION = "GRID_INTERSECTION"
    WALL_ALIGNMENT = "WALL_ALIGNMENT"
    CORE_ADJACENCY = "CORE_ADJACENCY"
    PERIMETER_CORNER = "PERIMETER_CORNER"
    STACKED_FROM_BELOW = "STACKED_FROM_BELOW"
    INFERRED_FROM_SPAN = "INFERRED_FROM_SPAN"


class ForbiddenReason(str, Enum):
    ELEVATOR_SHAFT = "ELEVATOR_SHAFT"
    STAIR_OPENING = "STAIR_OPENING"
    PRIMARY_CORRIDOR = "PRIMARY_CORRIDOR"
    LOBBY_CLEARANCE = "LOBBY_CLEARANCE"
    LARGE_OPENING_ZONE = "LARGE_OPENING_ZONE"
    ARCHITECTURAL_CONSTRAINT = "ARCHITECTURAL_CONSTRAINT"


class FramingDirection(str, Enum):
    X_PRIMARY = "X_PRIMARY"
    Y_PRIMARY = "Y_PRIMARY"
    BIDIRECTIONAL = "BIDIRECTIONAL"
    UNDETERMINED = "UNDETERMINED"


class GravitySystemType(str, Enum):
    RC_FLAT_SLAB = "RC_FLAT_SLAB"
    RC_BEAM_SLAB = "RC_BEAM_SLAB"
    RC_ONE_WAY_SLAB = "RC_ONE_WAY_SLAB"
    RC_TWO_WAY_SLAB = "RC_TWO_WAY_SLAB"
    STEEL_BEAM_COLUMN = "STEEL_BEAM_COLUMN"
    STEEL_COMPOSITE = "STEEL_COMPOSITE"
    POST_TENSIONED_SLAB = "POST_TENSIONED_SLAB"


class LateralSystemType(str, Enum):
    SHEAR_WALL = "SHEAR_WALL"
    BRACED_FRAME = "BRACED_FRAME"
    MOMENT_FRAME = "MOMENT_FRAME"
    CORE_WALL = "CORE_WALL"
    DUAL_SYSTEM = "DUAL_SYSTEM"


class ConstraintType(str, Enum):
    NO_SUPPORT_ZONE = "NO_SUPPORT_ZONE"
    REQUIRED_SUPPORT = "REQUIRED_SUPPORT"
    MAX_SPAN_LIMIT = "MAX_SPAN_LIMIT"
    MIN_SPAN_LIMIT = "MIN_SPAN_LIMIT"
    CORRIDOR_CLEARANCE = "CORRIDOR_CLEARANCE"
    VERTICAL_ALIGNMENT_REQUIRED = "VERTICAL_ALIGNMENT_REQUIRED"
    OPENING_AVOIDANCE = "OPENING_AVOIDANCE"
    FACADE_SETBACK = "FACADE_SETBACK"
    CORE_CONTINUITY = "CORE_CONTINUITY"
    TRANSFER_AVOIDANCE = "TRANSFER_AVOIDANCE"
    LATERAL_SYSTEM_REQUIRED = "LATERAL_SYSTEM_REQUIRED"


class ConstraintPriority(str, Enum):
    HARD = "hard"
    SOFT = "soft"
